name: 🐛 Bug Report
description: Report a problem or issue with the school management system
title: "[BUG] "
labels: ["bug", "teacher-request"]
assignees:
  - copilot
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide detailed information to help us fix the issue quickly.

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: What happened? Describe the problem clearly
      placeholder: "Describe what went wrong and what you expected to happen instead"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we recreate this bug?
      value: |
        1. Go to...
        2. Click on...
        3. Enter...
        4. See error
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: "Describe the correct behavior you expected"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Describe what actually occurred, including any error messages"
    validations:
      required: true

  - type: dropdown
    id: affected_area
    attributes:
      label: Which part of the system is affected?
      description: Select the area where you encountered the bug
      options:
        - Login/Authentication
        - Activity Registration
        - Activity List Display
        - Student Management
        - Activity Creation/Modification
        - General Navigation
        - Other (specify below)
    validations:
      required: true

  - type: input
    id: other_area
    attributes:
      label: Other Affected Area
      description: If you selected "Other" above, please specify
      placeholder: "Describe the specific area affected"

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser were you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this issue?
      options:
        - "Critical - System is unusable"
        - "High - Major functionality broken"
        - "Medium - Some features affected"
        - "Low - Minor issue"
    validations:
      required: true

  - type: textarea
    id: error_messages
    attributes:
      label: Error Messages
      description: Copy any error messages you see
      placeholder: "Paste any error messages, console errors, or unusual behavior"
      render: text

  - type: textarea
    id: user_account
    attributes:
      label: User Account Information
      description: Which teacher account were you using? (Do not include passwords)
      placeholder: "e.g., Username: mrodriguez, Role: teacher"

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How will you know this bug is fixed?
      value: |
        - [ ] The reported issue no longer occurs
        - [ ] Steps to reproduce work as expected
        - [ ] No new issues are introduced
        - [ ] Similar scenarios are tested and working
      render: markdown
    validations:
      required: true

  - type: textarea
    id: technical_context
    attributes:
      label: Technical Context for Developer
      value: |
        **System Architecture:**
        - Backend: FastAPI with MongoDB
        - Frontend: Vanilla HTML/CSS/JavaScript
        - Authentication: Simple username/password with session storage
        - Key files: `src/app.py`, `src/backend/`, `src/static/`
        
        **Common debugging steps:**
        1. Check browser console for JavaScript errors
        2. Verify API endpoints are responding correctly
        3. Check MongoDB data integrity
        4. Test authentication flow
      render: markdown

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that might help fix this bug?
      placeholder: "Screenshots, additional details, or context about when this started happening"